# Generated by Django 6.0.5 on 2026-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('kind', models.CharField(choices=[('otp', 'کد تأیید'), ('order', 'اطلاع\u200cرسانی سفارش'), ('admin', 'اطلاع به مدیر'), ('test', 'تست'), ('manual', 'ارسال دستی')], default='manual', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('skipped', 'ارسال نشد (غیرفعال)')], default='sent', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'گزارش پیامک',
                'verbose_name_plural': 'گزارش\u200cهای پیامک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('login', 'ورود / ثبت\u200cنام'), ('verify', 'تأیید شماره')], default='login', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کد یکبارمصرف',
                'verbose_name_plural': 'کدهای یکبارمصرف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used'], name='notificatio_phone_cc7939_idx')],
            },
        ),
    ]
