# Generated by Django 6.0.6 on 2026-08-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_product_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=30)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'تنوع سایز/رنگ',
                'verbose_name_plural': 'تنوع\u200cهای سایز/رنگ',
                'ordering': ['order', 'size', 'color'],
                'constraints': [models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_size_color')],
            },
        ),
    ]
