# Generated by Django 6.0.5 on 2026-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_compare_price_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, verbose_name='بارکد / EAN'),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, max_length=150, verbose_name='گارانتی'),
        ),
        migrations.AddField(
            model_name='product',
            name='include_in_feeds',
            field=models.BooleanField(default=True, verbose_name='نمایش در ترب و ایمالز'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='ویدیو معرفی'),
        ),
    ]
