# Generated by Django 6.0.6 on 2026-09-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_barcode_product_guarantee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
    ]
