# Generated by Django 6.0.6 on 2026-08-08 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartitem_unique_together_cartitem_variant_and_more'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('authority', ''), _negated=True), fields=('authority',), name='unique_nonempty_payment_authority'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('ref_id', ''), _negated=True), fields=('ref_id',), name='unique_nonempty_payment_ref_id'),
        ),
    ]
