# Generated by Django 6.0.6 on 2026-08-08 19:15

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[config.validators.validate_image_upload]),
        ),
    ]
