# Generated by Django 6.0.6 on 2026-09-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_feed_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
